name: build and test

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '7.x' # The .NET SDK version to use

jobs:
  build-and-test:

    name: Build and Test
    runs-on: ubuntu-22.04
   
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish Blazor
      run: dotnet publish -o out
      working-directory: BlazorApp

    - name: Save blazorApp artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: blazorapp
        path: BlazorApp/out

  deploy-blazorapp:
   name: Deploy Blazor App
   needs: build-and-test
   runs-on: ubuntu-22.04
   steps:
    - name: Download blazorApp artifact
      uses: actions/download-artifact@v3
      with:
        name: blazorapp

    - name: Deploy blazorapp to Azure
      uses: azure/webapps-deploy@v2
      with: 
        app-name: basketbtracker
        publish-profile: ${{ secrets.AZURE_BLAZORAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package:  ${{ github.workspace }}
     