name: build and test

on:
  push:
    paths-ignore:
    - '.github/workflows/Sql-deployment.yml'
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '8.x' # The .NET SDK version to use

jobs:
  build-and-test:

    name: Build and Test
    runs-on: windows-2022
   
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish API
      run: dotnet publish -o out
      working-directory: API

    - name: Save API artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: api
        path: API/out

    - name: Publish Blazor
      run: dotnet publish -o out
      working-directory: BlazorApp

    - name: Save blazorApp artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: blazorapp
        path: BlazorApp/out

  build-sql: 
    runs-on: windows-2022
    steps:
    - name: Checkout Repository     
      uses: actions/checkout@v4.1.0
  
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1    
  
    - name: Build DACPAC
      run: msbuild /p:TargetFrameworkVersion=v4.7.1 /p:DSP=Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider
      working-directory: BbPerformanceTrackerDb
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name:  SQLDB
        path: ${{ github.workspace }}/BbPerformanceTrackerDb/bin/debug/
  

  deploy-blazorapp:
   name: Deploy Blazor App
   needs: build-and-test
   runs-on: windows-2022
   steps:
    - name: Download blazorApp artifact
      uses: actions/download-artifact@v3
      with:
        name: blazorapp

    - name: Deploy blazorapp to Azure
      uses: azure/webapps-deploy@v2
      with: 
        app-name: basketbtracker
        publish-profile: ${{ secrets.AZURE_BLAZORAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package:  ${{ github.workspace }}
  
  deploy-api:
   name: Deploy API
   needs: build-and-test
   runs-on: windows-2022
   steps:
    - name: Download API artifact
      uses: actions/download-artifact@v3
      with:
        name: api

    - name: Deploy API to Azure
      uses: azure/webapps-deploy@v2
      with: 
        app-name: bbtrackerapi
        publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package:  ${{ github.workspace }}
     