name: deploy sql to Azure

on:
  workflow_dispatch:

jobs:
  deploy-sqldb-to-azure:

    name: Deploy SqlDb to Azure
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1    
  
      - name: Build DACPAC
        run: msbuild /p:TargetFrameworkVersion=v4.7.1 /p:DSP=Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider
        working-directory: BbPerformanceTrackerDb

      - name: Deploy 
        uses: Azure/sql-action@v2.2
        with:
          connection-string: Server=tcp:bbtrackerdb.database.windows.net,1433;Initial Catalog=BbData;Persist Security Info=False;User ID=kozanadmin;Password=${{secrets.AZURE_SQL_PASSWORD}};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
          path: ${{ github.workspace }}/BbPerformanceTrackerDb/bin/debug/BbPerformanceTrackerDb.dacpac
          action: Publish
          